version: '3'
services:
  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - 4000:3000
    environment:
      - DB_HOST=nestjs_mysql
      - DB_PORT=3309
      - DB_DATABASE=learn_nestjs
      - DB_USERNAME=user
      - DB_PASSWORD=pass1234
      - TZ=Asia/Kathmandu
    volumes:
      - '.:/var/www/nestjs'
    networks:
      - nestjs_network
    depends_on:
      - nestjs_db

  nestjs_db:
    image: 'mysql:8.0'
    container_name: nestjs_db
    ports:
      - 3009:3009
    environment:
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'nestjsdbdata:/var/lib/mysql'
    networks:
      - nestjs_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
      retries: 3
      timeout: 5s

  nestjs_pma:
    image: phpmyadmin
    container_name: nestjs_pma
    restart: always
    depends_on:
      - nestjs_db
    ports:
      - '8081:80'
    environment:
      PMA_HOST: nestjs_db
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      UPLOAD_LIMIT: 100M
    networks:
      - nestjs_network
networks:
  nestjs_network:
    driver: bridge

volumes:
  nestjsdbdata:
    driver: local
