FROM node:18.17.0-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /var/www/nestjs

COPY . .

RUN npm install
RUN npm run build
EXPOSE 3000
CMD ["node", "dist/main.js"]
# CMD ["npm", "run", "start:prod"]